### ISSUE TITLE
aosl.xcframework conflict with Agora-Flutter-SDK

### ISSUE THREAD

**Issue by vakrolme** [AgoraIO-Extensions/Agora-Flutter-RTM-SDK#175]
### Version of the agora_rtm

2.2.1 or `main` branch here

### Platforms affected

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] Web

### Steps to reproduce

clone [Agora-Flutter-SDK/example](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example). Update pubspec to add: 
```yaml
  agora_rtm: 2.2.1
```
Delete `aosl.xcframework` from Pods directory, as outlined [here](https://docs.agora.io/en/help/integration-issues/rtm2_rtc_integration_issue). Launch in debug mode. Use VScode or Xcode to build/run.

### Expected results

Project compiles and runs

### Actual results

Any `run` or `build` command launches pod install which re-installs `aosl.xcframework` and the process errors. 

Doing `pod deintegrate`, `flutter clean`, clearing cache, deleting pubspec and podfile `.lock` files, cleaning xcode build folder, updating cocoapods, nothing of that nature helps. 

When compiling from xcode, what happens a lot is also `The sandbox is not in sync with the Podfile.lock`, or `Module 'agora_rtc_engine' not found in flutter`.

### Logs

<details open><summary>Logs</summary>

```console

    -> Installing permission_handler_apple (9.1.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names: aosl.xcframework.
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:666:in `validate_targets' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:164:in `install!' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run' 
/Users/userk/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `' 
/Users/userk/.rbenv/versions/3.3.4/bin/pod:25:in `load' 
/Users/userk/.rbenv/versions/3.3.4/bin/pod:25:in `'
Error: Error running pod install

Exited (1).
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.93.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by HatsuneMikuV** [comment]
aosl.xcframework.

**Comment by devmuaz** [comment]
Hello @HatsuneMikuV @vakrolme,

To fix the issue mentioned above, add this block of code inside the `Podfile`:

**Note**: Add this block before the `post_install` block and NOT inside as both serve different purposes.

```ruby
pre_install do |installer|
  # Define the path for the AgoraRtm framework
  rtm_pod_path = File.join(installer.sandbox.root, 'AgoraRtm')
  # Full path to aosl.xcframework
  aosl_xcframework_path = File.join(rtm_pod_path, 'aosl.xcframework')
  # Check if the file exists, and if it does, delete it
  if File.exist?(aosl_xcframework_path)
    puts "Deleting aosl.xcframework from #{aosl_xcframework_path}"
    FileUtils.rm_rf(aosl_xcframework_path)
  else
    puts "aosl.xcframework not found, skipping deletion."
  end
end
```

After that, run `pod install` and everything should be resolved as expected!

For more information, please visit this page, which describes the issue and how to solve it.

[How do I handle issues when integrating the Signaling SDK and Video SDK simultaneously?](https://docs.agora.io/en/help/integration-issues/rtm2_rtc_integration_issue)

I hope this answer is helpful to all.
